version: '3'

services:
  frontend:
    build: 
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - lverity-network
    volumes:
      - ./web/Caddyfile:/etc/caddy/Caddyfile
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root123
      - DB_NAME=lverity
      - JWT_SECRET=abcdefghijklmnopq
    depends_on:
      db:
        condition: service_healthy
    networks:
      - lverity-network
    restart: unless-stopped

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=lverity
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - lverity-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot123"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  db-init:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: go run scripts/init_admin.go
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root123
      - DB_NAME=lverity
    depends_on:
      db:
        condition: service_healthy
    networks:
      - lverity-network

networks:
  lverity-network:
    driver: bridge

volumes:
  mysql-data:
  caddy_data:
  caddy_config:
